const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test'),ts=require('typescript'),React=require('react'),{renderToString}=require('react-dom/server');
const root=path.resolve(__dirname,'..');
function loader(overrides={},globals={}){const cache=new Map();return function load(file){file=path.resolve(root,file);if(cache.has(file))return cache.get(file);const ctx={exports:{},File,FormData,URL,process:{env:{NODE_ENV:'test'}},...globals,require(name){if(name==="server-only")return {};if(["@/app/asset-operations","@/app/handbook-actions"].includes(name))return new Proxy({},{get:()=>async()=>{}});if(Object.hasOwn(overrides,name))return overrides[name];if(name.startsWith('@/')||name.startsWith('./')){const target=name.startsWith('@/')?path.resolve(root,name.slice(2)):path.resolve(path.dirname(file),name);return load(target+(fs.existsSync(target+'.tsx')?'.tsx':'.ts'));}return require(name)}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,ctx,{filename:file});cache.set(file,ctx.exports);return ctx.exports;};}
const plain=value=>JSON.parse(JSON.stringify(value));

test('one File instance survives every destination step and close clears it',()=>{
 const {emptyHomeUpload,homeUploadReducer:r}=loader()('lib/home-upload-state.ts');const file=new File(['image'],'a.png',{type:'image/png'});
 for(const target of ['inspiration','shared','store']){let state=r(emptyHomeUpload,{type:'open',file,sourceUrl:'https://example.com/origin'});state=r(state,{type:'target',target});if(target==='store'){assert.equal(state.step,'store-picker');state=r(state,{type:'back'});assert.equal(state.file,file);state=r(state,{type:'target',target});state=r(state,{type:'store',id:'shop'});}assert.equal(state.file,file);assert.equal(state.sourceUrl,'https://example.com/origin');assert.equal(state.step,target);state=r(state,{type:'close'});assert.equal(state.file,null);assert.equal(state.storeId,null);assert.equal(state.sourceUrl,'');}
 assert.equal(r(emptyHomeUpload,{type:'open'}).step,'target');
});
function hookHarness(){const listeners=new Map(),cleanups=[],state=[];const react={useEffect:fn=>{const cleanup=fn();if(cleanup)cleanups.push(cleanup)},useState:initial=>[initial,value=>state.push(value)],useRef:()=>({current:null})};const globals={window:{addEventListener:(type,handler)=>listeners.set(type,handler),removeEventListener:(type)=>listeners.delete(type)},document:{querySelector:()=>null}};return{listeners,cleanups,state,react,globals};}
function transfer(file,values={}){return{items:file?[{kind:'file',type:file.type,getAsFile:()=>file}]:[],files:file?[file]:[],types:[],getData:type=>values[type]||''};}
test('clipboard ignores text and editable focus, parses provided source, and does not upload',()=>{
 const h=hookHarness(),hooks=loader({react:h.react},h.globals)('components/image-drop-zone.tsx');const file=new File(['a'],'a.png',{type:'image/png'}),received=[];hooks.useClipboardImage((...args)=>received.push(args));let prevented=0;const event={target:{closest:()=>null},clipboardData:transfer(null,{'text/plain':'hello'}),preventDefault:()=>prevented++};h.listeners.get('paste')(event);assert.equal(prevented,0);event.clipboardData=transfer(file,{'text/html':'<a href="https://example.com/page"><img src="https://example.com/image.png"></a>'});event.target={closest:()=>({})};h.listeners.get('paste')(event);assert.equal(received.length,0);event.target={isContentEditable:true};h.listeners.get('paste')(event);assert.equal(received.length,0);event.target={closest:()=>null};h.listeners.get('paste')(event);assert.equal(received[0][0],file);assert.equal(received[0][1],'https://example.com/page');assert.equal(prevented,1);h.cleanups.forEach(fn=>fn());assert.equal(h.listeners.size,0);
});
test('image drop prevents navigation and preserves File without inventing a URL',()=>{
 const h=hookHarness(),hooks=loader({react:h.react},h.globals)('components/image-drop-zone.tsx');const file=new File(['a'],'a.png',{type:'image/png'}),received=[];hooks.usePageImageDrop((...args)=>received.push(args),undefined,true,true);let prevented=0,stopped=0;const event={dataTransfer:transfer(file),preventDefault:()=>prevented++,stopPropagation:()=>stopped++};h.listeners.get('dragenter')(event);assert.equal(h.state.at(-1),true);h.listeners.get('drop')(event);assert.equal(prevented,2);assert.equal(stopped,2);assert.equal(received[0][0],file);assert.equal(received[0][1],undefined);assert.equal(h.state.at(-1),false);
});
test('preview object URL is revoked on unmount',()=>{const h=hookHarness();let created=0,revoked=[];const hooks=loader({react:h.react},{...h.globals,URL:{createObjectURL:()=>{created++;return'blob:test'},revokeObjectURL:url=>revoked.push(url)}})('components/image-drop-zone.tsx');hooks.useLocalImage(new File(['a'],'a.png'));assert.equal(created,1);h.cleanups.forEach(fn=>fn());assert.deepEqual(revoked,['blob:test']);});
test('home empty states, links, dates and monograms are safe without mock fillers',()=>{
 const load=loader({'@/app/actions':new Proxy({},{get:()=>async()=>{}}),'next/navigation':{useRouter:()=>({refresh(){}})}});const {HomeContent}=load('components/home-content.tsx');for(const value of [null,undefined,[],[null]]){const html=renderToString(React.createElement(HomeContent,{inspirations:value,stores:value,activities:value,tags:value,workstations:value,now:0}));assert.ok(html.includes('还没有灵感素材')&&html.includes('还没有店铺')&&html.includes('还没有最近更新'));assert.ok(html.includes('href="/library"')&&html.includes('href="/stores"'));assert.ok(!html.includes('unsplash'));}const {storeMonogram,homeDate,relativeTime}=load('lib/home-display.ts');assert.equal(storeMonogram(' 123 AMOISE'),'AM');assert.equal(storeMonogram('FGU'),'FG');assert.equal(storeMonogram(null),'店');assert.equal(homeDate('invalid'),'未记录');assert.equal(relativeTime(null,0),'未记录');
});
test('home server queries use real data, exact store counts and complete activity detail targets',async()=>{
 const queries=[];const rows={activities:[{id:'a1',target_type:'inspiration',target_id:'i',created_at:'2026-09-22',action:'inspiration_created'},{id:'a2',target_type:'shared_asset',target_id:'s',created_at:'2026-09-22',action:'shared_asset_created'},{id:'a3',target_type:'store_asset',target_id:'a',created_at:'2026-09-22',action:'store_asset_created'}],inspirations:[{id:'i',image_url:'/api/inspirations/i/image',created_at:'2026-09-22',inspiration_tags:null}],stores:[{id:'shop',name:'AMOISE',updated_at:'2026-09-20',asset_count:{count:37},asset_summary:[{asset_category:'scene',updated_at:'2026-09-22'}]}],shared_assets:[{id:'s',description:'备注',preview_file:{id:'f'},shared_asset_stores:null,shared_asset_workstations:null}],store_assets:[{id:'a',store_id:'shop',store:{id:'shop',name:'AMOISE'},asset_category:'scene',asset_files:[{id:'f2'}]}]};const client={from(table){const query={table};const q={select(fields){query.fields=fields;return q},in(){return q},is(field,value){query.active=[field,value];return q},order(field){query.order=field;return q},limit(value){query.limit=value;return q},then(resolve,reject){queries.push(query);return Promise.resolve({data:rows[table]||[],error:null}).then(resolve,reject)}};return q;}};const data=loader({'./supabase/server':{isSupabaseConfigured:()=>true,createClient:async()=>client}})('lib/data.ts');const inspirations=await data.getHomeInspirations(),stores=await data.getHomeStores(),activities=await data.getRecentActivities();assert.equal(inspirations[0].image,'/api/inspirations/i/image');assert.equal(queries[0].limit,8);assert.equal(stores[0].count,37);assert.equal(stores[0].updatedAt,'2026-09-22');assert.deepEqual(plain(queries.find(q=>q.table==='stores').active),['archived_at',null]);assert.ok(activities[0].inspiration);assert.equal(activities[1].asset.kind,'shared');assert.equal(activities[2].asset.kind,'store');assert.equal(activities[2].title,'新增副图');const empty=await loader({'./supabase/server':{isSupabaseConfigured:()=>false}})('lib/data.ts').getHomeData();assert.equal(empty.inspirations.length+empty.stores.length+empty.activities.length,0);
});

test('all three create actions tolerate audit failures but preserve business failure cleanup',async()=>{
 function database(failActivity=false, failRelation=false){const tables={profiles:[{id:'u',role:'member',is_disabled:false}],stores:[{id:'shop',archived_at:null}],inspirations:[],inspiration_tags:[],shared_assets:[],shared_asset_stores:[],shared_asset_workstations:[],store_assets:[],store_asset_tags:[],store_asset_workstations:[],asset_files:[],activities:[]};const paths=[],removed=[],logs=[];const client={auth:{getUser:async()=>({data:{user:{id:'u'}}})},from(table){let op='read',payload,conditions=[];const q={select(){return q},eq(k,v){conditions.push(row=>row[k]===v);return q},is(k,v){conditions.push(row=>row[k]===v);return q},in(k,vs){conditions.push(row=>vs.includes(row[k]));return q},insert(v){op='insert';payload=Array.isArray(v)?v:[v];return q},update(v){op='update';payload=v;return q},delete(){op='delete';return q},single(){return run(true)},then(resolve,reject){return run(false).then(resolve,reject)}};async function run(single){if(failRelation && ['inspiration_tags','shared_asset_stores','store_asset_tags'].includes(table)) return {data:null,error:{message:'relation denied'}};let data=(tables[table]||[]).filter(row=>conditions.every(fn=>fn(row)));if(op==='insert'){if(table==='activities'&&failActivity){if(failActivity==='throw')throw new Error('activity transport failed');return{data:null,error:{code:'42501',message:'activity denied'}};}data=payload.map((row,index)=>({id:table+'-'+index,...row}));tables[table].push(...data);}if(op==='update')data.forEach(row=>Object.assign(row,payload));if(op==='delete')tables[table]=tables[table].filter(row=>!data.includes(row));return{data:single?data[0]||null:data,error:null};}return q;}};const actions=loader({'@/lib/supabase/server':{createClient:async()=>client},'next/cache':{revalidatePath:p=>paths.push(p)},'@/lib/r2':{optimizeAndUploadImage:async()=>({key:'image',originalName:'a.png',mimeType:'image/png',sizeBytes:1,width:1,height:1}),removeObject:async key=>removed.push(key)}},{console:{error:(...args)=>logs.push(args)}})('app/actions.ts');return{tables,paths,removed,logs,actions};}
 for(const [method,type,path] of [['createInspiration','inspiration','/library'],['createSharedAsset','shared_asset','/shared'],['uploadStoreAsset','store_asset','/stores/shop']]){
  const d=database(),form=new FormData();form.set('image',new File(['x'],'a.png',{type:'image/png'}));form.set('category','scene');await(method==='uploadStoreAsset'?d.actions[method]('shop',form):d.actions[method](form));assert.equal(d.tables.activities.length,1);assert.equal(d.tables.activities[0].target_type,type);assert.equal(d.tables.activities[0].actor_id,'u');assert.equal(d.tables.activities[0].action,type+'_created');assert.ok(d.paths.includes('/')&&d.paths.includes(path));if(type!=='inspiration')assert.ok(d.paths.includes('/workstations'));assert.deepEqual(d.removed,[]);
  const table=type==='inspiration'?'inspirations':type==='shared_asset'?'shared_assets':'store_assets';
  for(const failure of [true,'throw']){const failing=database(failure);await(method==='uploadStoreAsset'?failing.actions[method]('shop',form):failing.actions[method](form));assert.deepEqual(failing.tables[table],d.tables[table]);assert.deepEqual(failing.tables.asset_files,d.tables.asset_files);assert.equal(failing.tables.activities.length,0);assert.deepEqual(failing.removed,[]);assert.ok(failing.paths.includes('/')&&failing.paths.includes(path));assert.equal(failing.logs.length,1);assert.equal(failing.logs[0][1].targetType,type);assert.equal(failing.logs[0][1].targetId,d.tables[table][0].id);assert.equal(failing.logs[0][1].actorId,'u');assert.equal(failing.logs[0][1].action,type+'_created');assert.match(failing.logs[0][1].error.message,/activity/);}
  const businessFailure=database(false,true);await assert.rejects(method==='uploadStoreAsset'?businessFailure.actions[method]('shop',form):businessFailure.actions[method](form),/relation denied/);assert.equal(businessFailure.tables[table].length,0);assert.deepEqual(businessFailure.removed,['image']);assert.equal(businessFailure.tables.activities.length,0);
 }
});
