const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict'),{test,before,after}=require('node:test');
let db;const A='10000000-0000-0000-0000-000000000001',B='10000000-0000-0000-0000-000000000002',ADMIN='10000000-0000-0000-0000-000000000003';let shop,other;
const q=(sql,args=[])=>db.query(sql,args);const one=async(sql,args=[])=>Object.values((await q(sql,args)).rows[0])[0];
async function as(id){await db.exec(`reset role; set role authenticated; set request.jwt.claim.sub='${id}';`)}
before(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
 await db.exec(fs.readFileSync('supabase/schema.sql','utf8').split('-- Shared materials extension')[0].replace('create extension if not exists pgcrypto;',''));
 for(const name of ['20260919_shared_assets.sql','20260919_r2_image_assets.sql','20260921_inspiration_details_activities.sql','20260921_archived_asset_store_read.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
 await db.exec(`grant usage on schema public to authenticated;grant select,insert,update,delete on all tables in schema public to authenticated;insert into auth.users values('${A}','a@test','{}'),('${B}','b@test','{}'),('${ADMIN}','admin@test','{}');update profiles set role='admin' where id='${ADMIN}';`);
 for(const name of ['20260923_v1_closeout.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
 await as(ADMIN);shop=await one("insert into stores(name,slug,created_by) values('AMOISE','amoise',auth.uid()) returning id");other=await one("insert into stores(name,slug,created_by) values('FGU','fgu',auth.uid()) returning id");
});
after(async()=>{await db?.close()});
async function asset(kind='store'){await as(A);const id=kind==='store'?await one('insert into store_assets(store_id,title,created_by) values($1,\'fixture\',auth.uid()) returning id',[shop]):await one("insert into shared_assets(title,created_by) values('fixture',auth.uid()) returning id");const f=await one(`insert into asset_files(${kind==='store'?'store_asset_id':'shared_asset_id'},original_name,storage_key,mime_type,size_bytes,kind,created_by) values($1,'test.png',$2,'image/webp',10,'image',auth.uid()) returning id`,[id,'fixture/'+id]);if(kind==='shared')await q('update shared_assets set preview_file_id=$1 where id=$2',[f,id]);return{id,f}}
let prompt,pt;
test('prompt team, private, favorite and search RLS include no admin private exception',async()=>{
 await as(A);pt=(await one("select v1_create_tag('prompt','MJ')")).id;prompt=await one("select v1_save_prompt(null,'private-canary mirror','team',$1::uuid[])",['{'+pt+'}']);
 await as(B);assert.equal(await one('select count(*)::int from prompts where id=$1',[prompt]),1);await q('insert into prompt_favorites values($1,auth.uid())',[prompt]);await assert.rejects(q('update prompts set content=\'bad\' where id=$1 returning id',[prompt]).then(r=>{if(!r.rows.length)throw Error('denied')}),/denied/);
 await as(ADMIN);assert.equal(await one('select count(*)::int from prompts where id=$1',[prompt]),1);await q('update prompts set content=\'private-canary mirror edited\' where id=$1',[prompt]);
 await as(A);await q("select v1_save_prompt($1,'private-canary mirror','private',$2::uuid[])",[prompt,'{'+pt+'}']);
 for(const user of [B,ADMIN]){await as(user);assert.equal(await one('select count(*)::int from prompts where id=$1',[prompt]),0);assert.equal(await one('select count(*)::int from prompt_tag_relations where prompt_id=$1',[prompt]),0);assert.equal(await one('select count(*)::int from prompt_favorites where prompt_id=$1',[prompt]),0);assert.deepEqual(await one("select v1_search_prompt_ids('private-canary')"),[]);assert.deepEqual(await one("select v1_search_prompt_ids('MJ')"),[]);await assert.rejects(q("select v1_save_prompt($1,'steal','team','{}')",[prompt]));await assert.rejects(q('insert into prompt_favorites values($1,auth.uid()) on conflict do nothing',[prompt]));}
 await as(A);assert.equal(await one('select count(*)::int from prompts where id=$1',[prompt]),1);await q('delete from prompts where id=$1',[prompt]);await db.exec('reset role');assert.equal(await one('select count(*)::int from prompt_favorites where prompt_id=$1',[prompt]),0);
});
test('tag pools isolate IDs, duplicate names return existing tags, member cannot rename/delete and admin batches rollback',async()=>{
 await as(A);const i=(await one("select v1_create_tag('inspiration','  Fixture  ')")).id;const s=(await one("select v1_create_tag('store','Fixture')")).id;const p=(await one("select v1_create_tag('prompt','Fixture')")).id;assert.equal(new Set([i,s,p]).size,3);assert.equal((await one("select v1_create_tag('store','fixture')")).id,s);assert.equal((await q("update store_tags set name='bad' where id=$1 returning id",[s])).rows.length,0);assert.equal((await q('delete from store_tags where id=$1 returning id',[s])).rows.length,0);await assert.rejects(q("select v1_manage_tags('store','[]','[]')"));
 const a=await asset();await q('insert into store_asset_tags values($1,$2)',[a.id,s]);await assert.rejects(q('insert into store_asset_tags values($1,$2)',[a.id,i]));await as(ADMIN);assert.equal(Number(await one("select v1_tag_usage('store',$1)",[s])),1);await assert.rejects(q("select v1_manage_tags('store','[]',$1::jsonb)",[JSON.stringify([{id:s,count:0}])]));await q("select v1_manage_tags('store','[]',$1::jsonb)",[JSON.stringify([{id:s,count:1}])]);assert.equal(await one('select count(*)::int from store_assets where id=$1',[a.id]),1);assert.equal(await one('select count(*)::int from asset_files where id=$1',[a.f]),1);
});
test('bidirectional move keeps file ID/workstations, removes old tags and atomically rolls back invalid target',async()=>{
 const a=await asset();const tag=(await one("select v1_create_tag('store','move-tag')")).id;await q('insert into store_asset_tags values($1,$2)',[a.id,tag]);await q('insert into store_asset_workstations values($1,2)',[a.id]);const shared=await one("select v1_move_asset('store',$1,$2::uuid[],'other','{}','{2}','note')",[a.id,'{'+shop+','+other+'}']);assert.equal(await one('select count(*)::int from store_assets where id=$1',[a.id]),0);assert.equal(await one('select shared_asset_id from asset_files where id=$1',[a.f]),shared);assert.equal(await one('select count(*)::int from store_asset_tags where store_asset_id=$1',[a.id]),0);assert.equal(await one('select count(*)::int from shared_asset_stores where shared_asset_id=$1',[shared]),2);
 await assert.rejects(q("select v1_move_asset('shared',$1,$2::uuid[],'main','{ffffffff-ffff-ffff-ffff-ffffffffffff}','{2}','')",[shared,'{'+shop+'}']));assert.equal(await one('select shared_asset_id from asset_files where id=$1',[a.f]),shared);
 const dest=await one("select v1_move_asset('shared',$1,$2::uuid[],'scene',$3::uuid[],'{2}','')",[shared,'{'+shop+'}','{'+tag+'}']);assert.equal(await one('select store_asset_id from asset_files where id=$1',[a.f]),dest);assert.equal(await one('select count(*)::int from shared_assets where id=$1',[shared]),0);assert.equal(await one('select count(*)::int from shared_asset_stores where shared_asset_id=$1',[shared]),0);assert.equal(await one('select count(*)::int from store_asset_workstations where store_asset_id=$1',[dest]),1);assert.equal(await one('select count(*)::int from r2_cleanup_queue where storage_key=$1',['fixture/'+a.id]),0);
});
test('shared removal only touches the selected store; permanent delete queues unreferenced file',async()=>{
 const a=await asset('shared');await q('insert into shared_asset_stores values($1,$2),($1,$3)',[a.id,shop,other]);await q("select v1_delete_asset('shared',$1,$2)",[a.id,shop]);assert.equal(await one('select count(*)::int from shared_asset_stores where shared_asset_id=$1',[a.id]),1);assert.equal(await one('select count(*)::int from asset_files where id=$1',[a.f]),1);await q("select v1_delete_asset('shared',$1)",[a.id]);assert.equal(await one('select count(*)::int from shared_asset_stores where shared_asset_id=$1',[a.id]),0);assert.equal(await one('select count(*)::int from asset_files where id=$1',[a.f]),0);assert.equal(await one('select count(*)::int from r2_cleanup_queue where storage_key=$1',['fixture/'+a.id]),1);
});
test('another member can detach a shared store relation but cannot move, edit or permanently delete the asset',async()=>{
 const a=await asset('shared');await q('insert into shared_asset_stores values($1,$2),($1,$3)',[a.id,shop,other]);
 await as(B);await q("select v1_delete_asset('shared',$1,$2)",[a.id,shop]);
 assert.deepEqual((await q('select store_id from shared_asset_stores where shared_asset_id=$1',[a.id])).rows.map(r=>r.store_id),[other]);
 assert.equal(await one('select created_by from shared_assets where id=$1',[a.id]),A);
 assert.equal(await one('select shared_asset_id from asset_files where id=$1',[a.f]),a.id);
 assert.equal(await one('select count(*)::int from r2_cleanup_queue where storage_key=$1',['fixture/'+a.id]),0);
 await assert.rejects(q("select v1_delete_asset('shared',$1)",[a.id]));
 await assert.rejects(q("select v1_move_asset('shared',$1,$2::uuid[],'main','{}','{}','')",[a.id,'{'+shop+'}']));
 assert.equal((await q('delete from shared_assets where id=$1 returning id',[a.id])).rows.length,0);
 assert.equal((await q("update shared_assets set description='bad' where id=$1 returning id",[a.id])).rows.length,0);
 await assert.rejects(q('insert into shared_asset_stores values($1,$2)',[a.id,shop]));
 await assert.rejects(q("select v1_delete_asset('shared',$1,$2)",[a.id,shop]));
 // Direct requests receive the same narrowly scoped RLS permission as the RPC.
 assert.equal((await q('delete from shared_asset_stores where shared_asset_id=$1 and store_id=$2 returning store_id',[a.id,other])).rows.length,1);
 await as('');await assert.rejects(q("select v1_delete_asset('shared',$1,$2)",[a.id,other]));
 await as(ADMIN);await q("select v1_delete_asset('shared',$1)",[a.id]);
 assert.equal(await one('select count(*)::int from shared_assets where id=$1',[a.id]),0);
});
test('file referenced by another business survives owner deletion and is collected after final reference',async()=>{
 const a=await asset('shared');await as(ADMIN);await q('update stores set cover_file_id=$1 where id=$2',[a.f,other]);await as(A);await q("select v1_delete_asset('shared',$1)",[a.id]);assert.equal(await one('select count(*)::int from asset_files where id=$1',[a.f]),1);assert.equal(await one('select count(*)::int from r2_cleanup_queue where storage_key=$1',['fixture/'+a.id]),0);await as(ADMIN);await q('update stores set cover_file_id=null where id=$1',[other]);assert.equal(await one('select count(*)::int from asset_files where id=$1',[a.f]),0);
});
test('members cannot move/delete other owners assets or fabricate R2 cleanup jobs',async()=>{
 const a=await asset();await as(B);await assert.rejects(q("select v1_delete_asset('store',$1)",[a.id]));await assert.rejects(q("select v1_move_asset('store',$1,'{}','other','{}','{}','')",[a.id]));await assert.rejects(q("insert into r2_cleanup_queue(storage_key,requested_by) values('victim',auth.uid())"));await assert.rejects(q('select v1_gc_file($1)',[a.f]));assert.equal(await one('select count(*)::int from store_assets where id=$1',[a.id]),1);
});
test('handbook admin CRUD/order, immutable general, member read-only and full-context search',async()=>{
 await as(ADMIN);const general=await one('select id from handbook_products where is_general');await assert.rejects(q("select v1_handbook_product('rename',$1,'bad')",[general]));await assert.rejects(q("select v1_handbook_product('delete',$1)",[general]));const product=await one("select v1_handbook_product('create',null,'Mirror')");const n1=await one("select v1_save_note(null,$1,'first note','{}','[]')",[product]);const n2=await one("select v1_save_note(null,$1,'canary note','{}','[]')",[product]);await q("select v1_reorder('note',$1,-1)",[n2]);assert.equal(await one('select id from handbook_notes where product_id=$1 order by sort_order limit 1',[product]),n2);assert.deepEqual(await one("select v1_search_handbook_ids('canary')"),[product]);
 await as(B);assert.equal(await one('select count(*)::int from handbook_notes where product_id=$1',[product]),2);await assert.rejects(q("select v1_handbook_product('create',null,'bad')"));await assert.rejects(q("select v1_save_note($1,$2,'bad','{}','[]')",[n1,product]));await assert.rejects(q("select v1_reorder('note',$1,1)",[n1]));assert.equal((await q('delete from handbook_notes where id=$1 returning id',[n1])).rows.length,0);
 await as(ADMIN);await q("select v1_handbook_product('delete',$1)",[product]);assert.equal(await one('select count(*)::int from handbook_notes where product_id=$1',[product]),0);
});
test('note images retain shared file references, removing final note image queues cleanup',async()=>{
 await as(ADMIN);const p=await one("select v1_handbook_product('create',null,'Images')");const files=JSON.stringify([{key:'notes/test',originalName:'ref.png',mimeType:'image/webp',sizeBytes:2,width:1,height:1}]);const n1=await one("select v1_save_note(null,$1,'one','{}',$2::jsonb)",[p,files]);const f=await one('select asset_file_id from handbook_note_images where note_id=$1',[n1]);const n2=await one("select v1_save_note(null,$1,'two','{}','[]')",[p]);await q('insert into handbook_note_images values($1,$2,0)',[n2,f]);await q('delete from handbook_notes where id=$1',[n1]);assert.equal(await one('select count(*)::int from asset_files where id=$1',[f]),1);await q('delete from handbook_notes where id=$1',[n2]);assert.equal(await one('select count(*)::int from asset_files where id=$1',[f]),0);assert.equal(await one("select count(*)::int from r2_cleanup_queue where storage_key='notes/test'"),1);
});
