import { StoreIdentity } from "@/components/store-identity";
import Link from "next/link";
import { ArrowUpRight, Store as StoreIcon } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { getStores, getSharedAssetCount, canEditWorkstations } from "@/lib/data";
import { NewStoreButton, StoreActions } from "@/components/store-management";

const categoryLabels: Record<string,string>={main:"主图",scene:"副图",a_plus:"A+",other:"其他"};
const date=(value?:string)=>value?new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value)).replaceAll("/","/"):"—";
export default async function StoresPage(){const [stores,sharedCount,canEdit]=await Promise.all([getStores(),getSharedAssetCount(),canEditWorkstations()]);return <AppShell active="店铺"><section className="mb-9 flex flex-wrap gap-4 items-end justify-between"><div><p className="text-xs font-medium text-zinc-500">店铺资产</p><h1 className="mt-2 text-4xl font-bold tracking-tight">店铺</h1><p className="mt-2 text-zinc-600">独立管理每个 Amazon 店铺的实际资产与源文件。</p></div>{canEdit&&<NewStoreButton/>}</section><div className="content-grid grid-three gap-6"><Link href="/shared" className="flex min-h-72 flex-col rounded-xl border border-orange-brand/30 bg-white p-5 shadow-card hover:shadow-float"><span className="grid h-14 w-14 place-items-center rounded-lg bg-orange-brand/10 text-lg font-semibold text-orange-brand">共享</span><h2 className="mt-7 text-lg font-bold">共享素材</h2><p className="mt-2 text-sm text-zinc-500">{sharedCount} 项共享素材</p><p className="mt-auto pt-6 text-sm text-zinc-500">团队通用与多店铺关联素材 →</p></Link>{stores.map(store=><article key={store.id} className="flex min-h-72 flex-col rounded-xl border border-zinc-200/70 bg-white p-5 shadow-card transition hover:shadow-float"><Link href={`/stores/${store.id}`} className="flex flex-1 flex-col"><div className="flex items-start justify-between"><StoreIdentity name={store.name} logo={store.logo}/><ArrowUpRight size={20} className="text-orange-brand"/></div><div className="mt-7"><div className="flex items-center gap-2"><h2 className="min-w-0 truncate text-lg font-bold" title={store.name}>{store.name}</h2><StoreIcon size={16} className="text-orange-brand"/></div><p className="mt-2 text-sm text-zinc-500">{store.count} 项店铺资产</p></div><div className="mt-6 min-h-6 text-sm text-zinc-500">{store.categories?.length?store.categories.map(c=>categoryLabels[c]||"其他").join(" · "):store.count?"共享素材":"暂无素材"}</div><p className="mt-auto pt-6 text-xs text-zinc-400">最近更新 · {date(store.updatedAt)}</p></Link><div className="mt-4 flex items-center justify-between border-t border-zinc-100 pt-4">{canEdit&&<StoreActions store={store}/>}<Link href={`/stores/${store.id}`} className="text-sm text-zinc-500 hover:text-orange-brand">进入店铺 →</Link></div></article>)}</div></AppShell>}
