"use client";
import {ActionMenu} from "./action-menu";

import {useEffect,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {savePrompt,deletePrompt,favoritePrompt,readPrompt} from "@/app/handbook-actions";
import {filterPrompts,canManagePrompt} from "@/lib/handbook-filters";
import {relationMany} from "@/lib/relation-values";
import {userError} from "@/lib/user-error";
import {TagFilter,filterClass} from "./tag-filter";
import {TagEditor} from "./asset-detail-modal";
import {Modal} from "./modal";
import {useTeam,useTagPool} from "./team-context";
import {useToast} from "./toast";
import type {Prompt,Tag} from "@/lib/types";
function PromptEditor({item,onClose}:{item?:Prompt;onClose:()=>void}){
 const {profile}=useTeam();const tags=useTagPool("prompt"),router=useRouter(),toast=useToast();const [pending,start]=useTransition(),[error,setError]=useState("");
 return <Modal title={item?"编辑提示词":"新建提示词"} pending={pending} onClose={onClose}><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);start(async()=>{try{await savePrompt(item?.id||null,form);router.refresh();toast({message:"提示词已保存"});onClose()}catch(e){setError(userError(e))}});}} className="space-y-5"><fieldset disabled={pending} className="space-y-5"><label className="block text-sm">提示词正文<textarea name="content" required defaultValue={item?.content||""} rows={10} className="mt-2 w-full resize-y rounded-lg border p-3"/></label><TagEditor scope="prompt" tags={tags} selected={item?.tags}/><label className="block text-sm">可见范围<select name="visibility" defaultValue={item?.visibility||"team"} className="mt-2 w-full rounded border p-3"><option value="team">团队共享</option>{(!item||item.createdBy===profile.id)&&<option value="private">仅自己</option>}</select></label></fieldset>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-3"><button type="button" disabled={pending} onClick={onClose} className="round-button">取消</button><button disabled={pending} className="round-button">{pending?"保存中…":"保存"}</button></div></form></Modal>
}
function PromptControls({item,onEdited}:{item:Prompt;onEdited?:()=>void}){
 const {profile}=useTeam(),router=useRouter(),toast=useToast();const [edit,setEdit]=useState(false),[confirm,setConfirm]=useState(false),[error,setError]=useState("");const [pending,start]=useTransition();const [copyMessage,setCopyMessage]=useState("");const manage=canManagePrompt(item,profile.id,profile.role==="admin");
 const copy=()=>start(async()=>{try{const current=await readPrompt(item.id);await navigator.clipboard.writeText(current.content);setCopyMessage("已复制");toast({message:"已复制"})}catch{setCopyMessage("复制失败，请重试");toast({message:"复制失败，请重试",error:true})}});
 return <><div className="mt-4 flex items-center gap-3 text-sm"><button type="button" disabled={pending} aria-pressed={item.favorite} onClick={()=>start(async()=>{try{await favoritePrompt(item.id,!item.favorite);router.refresh();onEdited?.()}catch(e){toast({message:userError(e),error:true})}})} className="text-zinc-500 hover:text-orange-brand">{item.favorite?"★ 已收藏":"☆ 收藏"}</button><button type="button" disabled={pending} onClick={copy} className="text-orange-brand">复制</button>{copyMessage&&<span role="status" className="text-xs">{copyMessage}</span>}{manage&&<ActionMenu label="提示词操作" className="ml-auto"><button type="button" onClick={()=>setEdit(true)} className="block w-full p-2 text-left">编辑</button><button type="button" onClick={()=>{setConfirm(true);setError("")}} className="block w-full p-2 text-left text-red-600">删除</button></ActionMenu>}</div>{edit&&<PromptEditor item={item} onClose={()=>{setEdit(false);onEdited?.()}}/>}{confirm&&<Modal title="删除提示词" pending={pending} onClose={()=>setConfirm(false)}><p className="text-sm text-zinc-600">删除后将从提示词库和相关用户收藏中移除。</p>{error&&<p role="alert" className="mt-3 text-red-600">{error}</p>}<div className="mt-5 flex justify-end gap-3"><button type="button" disabled={pending} className="round-button" onClick={()=>setConfirm(false)}>取消</button><button type="button" disabled={pending} className="round-button text-red-600" onClick={()=>start(async()=>{try{await deletePrompt(item.id);setConfirm(false);router.refresh();onEdited?.();toast({message:"提示词已删除"})}catch(e){setError(userError(e))}})}>{pending?"删除中…":"删除"}</button></div></Modal>}</>
}
export function PromptDetail({id,onClose}:{id:string;onClose:()=>void}){
 const [item,setItem]=useState<Prompt|null>(null),[error,setError]=useState("");
 useEffect(()=>{let stale=false;readPrompt(id).then(p=>{if(!stale)setItem(p)}).catch(e=>{if(!stale)setError(userError(e))});return()=>{stale=true}},[id]);
 return <Modal title="提示词详情" onClose={onClose}>{error?<p role="alert" className="text-red-600">{error}</p>:!item?<p>加载中…</p>:<><p className="whitespace-pre-wrap break-words text-sm leading-7">{item.content}</p><div className="mt-5 flex flex-wrap gap-2">{item.tags.map(t=><span key={t.id} className="meta-pill max-w-56 truncate">{t.name}</span>)}</div><p className="mt-3 text-xs text-zinc-400">{item.visibility==="team"?"团队共享":"仅自己"}</p><PromptControls item={item} onEdited={onClose}/></>}</Modal>
}
export function PromptBrowser({items,tags,initialTag,initialQuery="",initialId}:{items:Prompt[];tags:Tag[];initialTag?:string;initialQuery?:string;initialId?:string}){
 const [query,setQuery]=useState(initialQuery),[mode,setMode]=useState("all"),[selectedTags,setSelectedTags]=useState(initialTag?[initialTag]:[]),[selected,setSelected]=useState<string|null>(initialId||null),[create,setCreate]=useState(false);const {profile}=useTeam();const visible=filterPrompts(items,mode,query,selectedTags,profile.id);const router=useRouter();
 useEffect(()=>{const refresh=()=>router.refresh();window.addEventListener("focus",refresh);return()=>window.removeEventListener("focus",refresh)},[router]);
 useEffect(()=>{setSelectedTags(initialTag?[initialTag]:[]);setQuery(initialQuery);setSelected(initialId||null)},[initialTag,initialQuery,initialId]);
 return <><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><input aria-label="搜索提示词" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索正文或标签" className="w-full max-w-md rounded-full border px-4 py-2"/><button type="button" onClick={()=>setCreate(true)} className="round-button border-orange-brand bg-orange-brand text-white">+ 新建提示词</button></div><nav className="mb-5 flex gap-2">{[['all','全部'],['mine','我的'],['favorites','收藏']].map(([v,l])=><button type="button" key={v} onClick={()=>setMode(v)} className={filterClass(mode===v)}>{l}</button>)}</nav><TagFilter scope="prompt" tags={tags} selected={selectedTags} onChange={setSelectedTags}/>{!visible.length&&<p className="py-16 text-center text-zinc-500">{mode==="favorites"&&!query&&!selectedTags.length?"还没有收藏的提示词。":query||selectedTags.length?"没有找到相关结果。":"还没有提示词。"}</p>}<div className="content-grid grid-prompts items-start gap-5">{relationMany(visible).map(p=><article key={p.id} className="min-w-0 rounded-xl border border-zinc-200 bg-white p-5 shadow-card"><button type="button" onClick={()=>setSelected(p.id)} className="block w-full text-left"><p className="line-clamp-6 whitespace-pre-wrap break-words text-sm leading-7">{p.content}</p></button><div className="mt-4 flex flex-wrap gap-2">{relationMany(p.tags).map(t=><span key={t.id} className="meta-pill max-w-48 truncate">{t.name}</span>)}</div><p className="mt-3 text-xs text-zinc-400">{p.visibility==="team"?"团队共享":"仅自己"}</p><PromptControls item={p}/></article>)}</div>{create&&<PromptEditor onClose={()=>setCreate(false)}/>} {selected&&<PromptDetail id={selected} onClose={()=>setSelected(null)}/>}</>
}
