"use client";
import { ChevronRight, Folder, Grid2X2, BookOpen, Home, Monitor, Store, UserRound } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { SidebarProfile, Store as StoreType } from "@/lib/types";

export function SidebarNav({ active, activeStoreId, profile, stores }: { active: string; activeStoreId?: string; profile: SidebarProfile; stores: StoreType[] }) {
  const [open, setOpen] = useState(active === "店铺");
  useEffect(() => { if (active === "店铺") setOpen(true); }, [active]);
  const main = (isActive: boolean) => `flex items-center gap-3 rounded-full px-4 py-2.5 text-sm transition ${isActive ? "bg-orange-brand font-medium text-white" : "text-zinc-400 hover:bg-zinc-800 hover:text-white"}`;
  return <aside className="app-sidebar fixed inset-y-0 left-0 z-50 w-72 flex-col justify-between bg-[#111111] px-6 py-8 text-white shadow-2xl"><div><div className="mb-7 flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-orange-brand"><Grid2X2 size={15}/></span><span className="text-lg font-bold tracking-wide">火麦-素材共享</span></div><nav className="space-y-1"><Link href="/" className={main(active === "首页")}><Home size={18}/>首页</Link><Link href="/library" className={main(active === "素材库")}><Folder size={18}/>素材库</Link><div><div className={main(active === "店铺")}><Link href="/stores" className="-my-2.5 -ml-4 flex flex-1 items-center gap-3 px-4 py-2.5"><Store size={18}/>店铺</Link><button aria-label={open ? "收起店铺" : "展开店铺"} onClick={() => setOpen(value => !value)} className="-mr-2 rounded p-1 hover:bg-black/10"><ChevronRight size={15} className={`transition-transform ${open ? "rotate-90" : ""}`}/></button></div>{open && <div className="ml-5 mt-1 max-h-44 space-y-0.5 overflow-y-auto border-l border-zinc-800 py-1">{stores.map(store => <Link key={store.id} href={`/stores/${store.id}`} className={`flex items-center gap-2 px-3 py-1.5 text-sm transition ${activeStoreId === store.id ? "bg-zinc-800/70 text-orange-brand" : "text-zinc-500 hover:text-white"}`}><span className={`h-1.5 w-1.5 rounded-full ${activeStoreId === store.id ? "bg-orange-brand" : "bg-zinc-700"}`}/><span className="truncate">{store.name}</span></Link>)}</div>}</div><Link href="/handbook" className={main(active === "创作手册")}><BookOpen size={18}/>创作手册</Link><Link href="/workstations" className={main(active === "工作站")}><Monitor size={18}/>工作站</Link></nav></div><div className="flex items-center gap-3 border-t border-zinc-800 pt-5"><span className="grid h-9 w-9 place-items-center rounded-full border border-zinc-700 bg-zinc-800 text-orange-brand"><UserRound size={18}/></span><div className="min-w-0"><p className="truncate text-sm font-medium">{profile.displayName}</p><p className="text-xs text-zinc-400">{profile.role === "admin" ? "管理员" : "成员"}</p></div></div></aside>;
}
