"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {batchStoreAssets} from "@/app/actions";
import {userError} from "@/lib/user-error";
import {Modal} from "./modal";
import {assetCategories} from "./asset-detail-modal";
import {useToast} from "./toast";
export function BatchAssetBar({storeId,parents,active,selected,eligible,onSelect,onActive}:{storeId:string;parents:{id:string;name:string}[];active:boolean;selected:string[];eligible:string[];onSelect:(ids:string[])=>void;onActive:(value:boolean)=>void}){
 const [operation,setOperation]=useState(""),[error,setError]=useState(""),[pending,start]=useTransition(),router=useRouter(),toast=useToast();
 const operations=[["set_parent","归入父体"],["clear_parent","移出父体"],["category","修改分类"],["delete","删除"]];
 if(!active)return <div className="mb-5"><button type="button" className="round-button" onClick={()=>onActive(true)}>批量管理</button></div>;
 return <><div className="sticky top-0 z-20 mb-5 flex flex-wrap items-center gap-2 rounded-xl border bg-white/95 p-3 text-sm"><span>已选择 {selected.length} 张</span><button type="button" className="round-button" onClick={()=>onSelect(eligible.slice(0,100))}>选择当前已加载结果（最多100张）</button><button type="button" className="round-button" onClick={()=>onSelect([])}>清空</button>{operations.map(([value,label])=><button type="button" key={value} disabled={!selected.length} className="round-button disabled:opacity-40" onClick={()=>{setOperation(value);setError("")}}>{label}</button>)}<button type="button" className="round-button" onClick={()=>onActive(false)}>退出</button></div>{operation&&<Modal title={operations.find(x=>x[0]===operation)?.[1]||"批量管理"} onClose={()=>setOperation("")} pending={pending}><form onSubmit={e=>{e.preventDefault();start(async()=>{try{const form=new FormData(e.currentTarget);const count=await batchStoreAssets(storeId,selected,operation,String(form.get("value")||""),[]);onSelect([]);setOperation("");router.refresh();toast({message:`已更新 ${count} 张素材`})}catch(e){setError(userError(e,"批量操作失败，未对素材进行部分修改。"));router.refresh()}})}}><fieldset disabled={pending} className="space-y-4"><p>将处理已选择的 {selected.length} 张店铺素材。</p>{operation==="delete"&&<p className="text-red-600">确认删除这些素材？删除无法撤销，未被其他内容引用的图片将进入安全清理。</p>}{operation==="clear_parent"&&<p>只解除父体关系，图片继续保留在当前店铺。</p>}{operation==="set_parent"&&<select required name="value" className="w-full rounded border p-3"><option value="">请选择父体</option>{parents.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}{operation==="category"&&<select required name="value" className="w-full rounded border p-3">{assetCategories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}</fieldset>{error&&<p role="alert" className="mt-4 text-red-600">{error}</p>}<div className="mt-5 flex justify-end gap-3"><button type="button" disabled={pending} className="round-button" onClick={()=>setOperation("")}>取消</button><button disabled={pending} className="round-button">{pending?"处理中…":"确认"}</button></div></form></Modal>}</>;
}
