"use client";
import { userError } from "@/lib/user-error";
import { useState, useTransition } from "react";
import { Edit3, Plus, Trash2, X } from "lucide-react";
import { archiveStore, createStore, updateStore } from "@/app/actions";
import type { Store } from "@/lib/types";
import { useToast } from "./toast";

function StoreDialog({ store, onClose }: { store?: Store; onClose: () => void }) {
  const [pending, start] = useTransition(); const [error, setError] = useState(""); const toast = useToast();
  function submit(form: FormData) { start(async () => { setError(""); try { if (store) await updateStore(store.id, form); else await createStore(form); toast({ message: store ? "店铺已更新" : "店铺创建成功" }); onClose(); } catch (e) { setError(userError(e)); } }); }
  return <div className="fixed inset-0 z-[60] grid place-items-center bg-black/35 p-5 backdrop-blur-sm"><form onSubmit={event=>{event.preventDefault();submit(new FormData(event.currentTarget));}} className="max-h-[90dvh] w-full max-w-md overflow-y-auto rounded-2xl border border-zinc-200 bg-white p-6 shadow-float"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{store ? "编辑店铺" : "新建店铺"}</h2><button type="button" onClick={onClose} disabled={pending} className="rounded-full p-1 text-zinc-500 hover:bg-zinc-100"><X size={20}/></button></div><label className="mt-6 block text-sm font-medium">店铺名称<input name="name" required defaultValue={store?.name} className="mt-2 w-full rounded-xl border border-zinc-200 px-3 py-2.5 outline-none focus:border-orange-brand"/></label><label className="mt-4 block text-sm font-medium">备注<input name="description" defaultValue={store?.recent === "暂无素材" ? "" : store?.recent} className="mt-2 w-full rounded-xl border border-zinc-200 px-3 py-2.5 outline-none focus:border-orange-brand"/></label>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} disabled={pending} className="round-button">取消</button><button disabled={pending} className="round-button border-orange-brand bg-orange-brand text-white hover:bg-orange-deep disabled:opacity-60">{pending ? (store ? "保存中…" : "创建中…") : (store ? "保存" : "创建")}</button></div></form></div>;
}
export function NewStoreButton() { const [open,setOpen]=useState(false); return <>{open && <StoreDialog onClose={()=>setOpen(false)}/>}<button onClick={()=>setOpen(true)} className="round-button border-orange-brand bg-orange-brand text-white hover:bg-orange-deep"><Plus size={18}/>新建店铺</button></>; }
export function StoreActions({ store }: { store: Store }) { const [open,setOpen]=useState(false); const [pending,start]=useTransition(); const toast=useToast(); function archive(){if(!window.confirm(`归档「${store.name}」？店铺将从活跃列表隐藏，历史素材保留。`))return;start(async()=>{try{await archiveStore(store.id);toast({message:"店铺已归档"});}catch(e){toast({message:userError(e),error:true});}})} return <>{open && <StoreDialog store={store} onClose={()=>setOpen(false)}/>}<div className="flex gap-3"><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-1 text-xs text-zinc-500 hover:text-orange-brand"><Edit3 size={13}/>编辑</button><button disabled={pending} onClick={archive} className="inline-flex items-center gap-1 text-xs text-zinc-400 hover:text-red-600"><Trash2 size={13}/>归档</button></div></>; }
