import "server-only";
import {createClient,isSupabaseConfigured} from "./supabase/server";
import {relationMany,relationOne} from "./relation-values";
import type {HandbookProduct,Prompt} from "./types";
export const promptSelect="id,content,visibility,created_by,updated_at,prompt_tag_relations(tags:prompt_tags(id,name,group_name,color)),prompt_favorites(user_id)";
export function normalizePrompt(p:any):Prompt{return {id:p?.id,content:typeof p?.content==="string"?p.content:"",visibility:p?.visibility==="private"?"private":"team",createdBy:p?.created_by,updatedAt:p?.updated_at||"",tags:relationMany<any>(p?.prompt_tag_relations).map(r=>relationOne<any>(r.tags)).filter(Boolean),favorite:relationMany(p?.prompt_favorites).length>0}}
export async function getPrompts(ids?:string[]){if(!isSupabaseConfigured())return {ready:false,items:[] as Prompt[]};const s=await createClient();let query=s.from("prompts").select(promptSelect).order("updated_at",{ascending:false});if(ids)query=query.in("id",ids);const {data,error}=await query;if(error){if(["42P01","PGRST205"].includes(error.code))return {ready:false,items:[] as Prompt[]};throw new Error("提示词读取失败，请重试。")}return {ready:true,items:relationMany<any>(data).map(normalizePrompt)}}
export async function getHandbook(ids?:string[]){if(!isSupabaseConfigured())return {ready:false,products:[] as HandbookProduct[]};const s=await createClient();let query=s.from("handbook_products").select("id,name,is_general,updated_at,sort_order,handbook_notes(id,product_id,content,sort_order,updated_at,created_at,handbook_note_images(asset_file_id,sort_order))").order("is_general",{ascending:false}).order("sort_order").order("created_at");if(ids)query=query.in("id",ids);const {data,error}=await query;if(error){if(["42P01","PGRST205"].includes(error.code))return {ready:false,products:[] as HandbookProduct[]};throw new Error("作图规范读取失败，请重试。")}const products:HandbookProduct[]=relationMany<any>(data).map(p=>({id:p.id,name:p.name,general:p.is_general,updatedAt:p.updated_at,notes:relationMany<any>(p.handbook_notes).sort((a,b)=>a.sort_order-b.sort_order||String(a.created_at).localeCompare(b.created_at)||String(a.id).localeCompare(b.id)).map(n=>({id:n.id,productId:n.product_id,content:n.content||"",updatedAt:n.updated_at,images:relationMany<any>(n.handbook_note_images).sort((a,b)=>a.sort_order-b.sort_order).map(i=>({id:i.asset_file_id,image:'/api/media/'+i.asset_file_id}))}))}));return {ready:true,products}}

export async function searchHandbookModules(query:string){
 const s=await createClient();const [rules,prompts]=await Promise.all([s.rpc("v1_search_handbook_ids",{p_query:query}),s.rpc("v1_search_prompt_ids",{p_query:query})]);
 for(const r of [rules,prompts])if(r.error&&!['PGRST202','42883'].includes(r.error.code))throw new Error("搜索暂时不可用，请稍后重试");
 const [handbook,promptData]=await Promise.all([rules.data?.length?getHandbook(rules.data):Promise.resolve({products:[]}),prompts.data?.length?getPrompts(prompts.data):Promise.resolve({items:[]})]);return {handbook:handbook.products,prompts:promptData.items};
}
