"use client";
import Link from "next/link";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {registrationError} from "@/lib/team-members";
import {authError} from "@/lib/auth-flow";
export function RegisterForm({confirmationError=false}:{confirmationError?:boolean}){
 const [pending,setPending]=useState(false),[error,setError]=useState(confirmationError?"确认链接无效或已过期，请在申请时使用的浏览器打开最新邮件，或联系管理员。":""),[sent,setSent]=useState(false);
 return <>{sent?<p role="status" className="mt-8 text-sm leading-6 text-zinc-600">注册请求已提交。若邮箱可以注册，请查收确认邮件，并在当前浏览器打开链接。若已有账号，请直接登录或使用忘记密码。</p>:<form noValidate className="mt-8 space-y-4" onSubmit={async event=>{event.preventDefault();if(pending)return;const form=new FormData(event.currentTarget),name=String(form.get("username")||"").trim(),email=String(form.get("email")||"").trim(),password=String(form.get("password")||""),code=String(form.get("invite_code")||"").trim().toUpperCase(),invalid=registrationError(name,email,password,code);setError(invalid);if(invalid)return;setPending(true);try{const {data,error}=await createClient().auth.signUp({email,password,options:{emailRedirectTo:new URL("/auth/confirm",window.location.origin).href,data:{display_name:name,invite_code:code}}});if(error)throw error;if(data.session){window.location.href="/"}else{setSent(true)}}catch(e){setError(authError(e,"注册失败，请确认邀请码有效且未过期；若仍失败，请联系管理员。"))}finally{setPending(false)}}}><fieldset disabled={pending} className="space-y-4">{[{name:"username",label:"用户名",type:"text",autoComplete:"nickname"},{name:"email",label:"邮箱",type:"email",autoComplete:"email"},{name:"password",label:"密码",type:"password",autoComplete:"new-password"},{name:"invite_code",label:"邀请码",type:"text",autoComplete:"off"}].map(field=><label key={field.name} className="block text-sm">{field.label}<input name={field.name} type={field.type} autoComplete={field.autoComplete} required maxLength={field.name==="username"?80:undefined} className="mt-2 w-full rounded-xl border px-4 py-3"/></label>)}</fieldset>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={pending} className="w-full rounded-full bg-orange-brand py-3 text-white disabled:opacity-60">{pending?"注册中…":"注册"}</button></form>}<div className="mt-6 flex gap-5 text-sm text-orange-brand"><Link href="/login">返回登录</Link><Link href="/forgot-password">忘记密码？</Link></div></>;
}
