"use client";
import Link from "next/link";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {authError,emailError} from "@/lib/auth-flow";
export function LoginForm({unavailable=false}:{unavailable?:boolean}){
 const [error,setError]=useState(unavailable?"账号不可用或已停用，请联系管理员。":""),[pending,setPending]=useState(false);
 return <><form noValidate onSubmit={async event=>{event.preventDefault();if(pending)return;const form=new FormData(event.currentTarget),email=String(form.get("email")||"").trim(),password=String(form.get("password")||"");const invalid=emailError(email)||(!password?"请输入密码。":"");setError(invalid);if(invalid)return;setPending(true);try{const s=createClient();const {error}=await s.auth.signInWithPassword({email,password});if(error)throw error;const status=await s.rpc("is_active_member");if(status.error||status.data!==true){await s.auth.signOut({scope:"local"});setError("账号不可用或已停用，请联系管理员。");return}location.href="/"}catch(e){setError(authError(e,"登录失败，请稍后重试。"))}finally{setPending(false)}}} className="mt-8 space-y-4"><input aria-label="邮箱" required name="email" type="email" autoComplete="email" placeholder="邮箱" className="w-full rounded-xl border border-zinc-200 bg-white px-4 py-3 outline-none focus:border-orange-brand"/><input aria-label="密码" required name="password" type="password" autoComplete="current-password" placeholder="密码" className="w-full rounded-xl border border-zinc-200 bg-white px-4 py-3 outline-none focus:border-orange-brand"/>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={pending} className="w-full rounded-full bg-orange-brand py-3 font-medium text-white hover:bg-orange-deep disabled:opacity-60">{pending?"登录中…":"登录火麦-素材共享"}</button></form><div className="mt-5 text-center text-sm"><Link href="/forgot-password" className="text-orange-brand hover:underline">忘记密码？</Link><Link href="/register" className="ml-5 text-orange-brand hover:underline">注册账号</Link></div></>;
}
